# Generated by Django 3.0.5 on 2020-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0002_historicalscan_historicalscanfolder_historicalscanrootfolder_scan_scanfolder_scanrootfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='orientation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='orientation',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
