# Generated by Django 3.0.1 on 2020-09-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0003_auto_20200814_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalscanfolder',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalscanfolder',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scanfolder',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanfolder',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
