# Generated by Django 3.1.2 on 2020-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0004_auto_20200929_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='length',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='length',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='length',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='length',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
