# Generated by Django 3.1.2 on 2020-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0005_auto_20201007_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='desktop_fpp',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='desktop_select_mode',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='desktop_show_filterBar',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='desktop_show_infoColumn',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='desktop_show_toolBar',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='mobile_fpp',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='mobile_select_mode',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='mobile_show_filterBar',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='mobile_show_infoColumn',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='mobile_show_toolBar',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='desktop_page_size',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000')], default='100'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='mobile_page_size',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000')], default='25'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='desktop_thumb_scale',
            field=models.FloatField(default=0.4),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='mobile_thumb_scale',
            field=models.FloatField(default=0.2),
        ),
    ]
