# Generated by Django 3.1.2 on 2021-01-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0007_auto_20201230_1552'),
        ('fileserver', '0006_auto_20201201_1833'),
    ]

    operations = [
    ]
