# Generated by Django 3.1.2 on 2021-01-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0009_auto_20210113_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='access_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fileserver.authgroup'),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='access_group',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fileserver.authgroup'),
        ),
    ]
