# Generated by Django 3.1.2 on 2021-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0010_auto_20210117_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='access_group',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='access_group',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='access_group',
        ),
        migrations.RemoveField(
            model_name='historicalfolder',
            name='access_group',
        ),
        migrations.AddField(
            model_name='file',
            name='access_groups',
            field=models.ManyToManyField(related_name='_file_access_groups_+', to='fileserver.AuthGroup'),
        ),
        migrations.AddField(
            model_name='folder',
            name='access_groups',
            field=models.ManyToManyField(related_name='_folder_access_groups_+', to='fileserver.AuthGroup'),
        ),
    ]
