# Generated by Django 3.1.2 on 2022-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0011_auto_20211226_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroup',
            name='can_link',
            field=models.BooleanField(default=False),
        ),
    ]
