# Generated by Django 3.1.2 on 2023-01-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0013_auto_20221227_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='allow_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='allow_upload',
            field=models.BooleanField(default=False),
        ),
    ]
